
import java.awt.Color;
import java.awt.Font;
import java.awt.Image;
import java.awt.Toolkit;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.io.PrintWriter;
import java.net.URL;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JTextArea;
import javax.swing.filechooser.FileNameExtensionFilter;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author aluno
 */
public class bloco extends javax.swing.JFrame {
   
   
    /**
     * Creates new form bloco
     */
    public bloco() {
        initComponents();
        setIcon();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtarea = new javax.swing.JTextArea();
        jMenuBar1 = new javax.swing.JMenuBar();
        jarquivo = new javax.swing.JMenu();
        jabrir = new javax.swing.JMenuItem();
        jnovo = new javax.swing.JMenuItem();
        jsalvar = new javax.swing.JMenuItem();
        jeditar = new javax.swing.JMenu();
        jcopiar = new javax.swing.JMenuItem();
        jrecortar = new javax.swing.JMenuItem();
        jcolar = new javax.swing.JMenuItem();
        jselecionar = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        jpesonalizar = new javax.swing.JMenu();
        jitempreto = new javax.swing.JMenuItem();
        jitemvermelho = new javax.swing.JMenuItem();
        jitemazul = new javax.swing.JMenuItem();
        jitemverde = new javax.swing.JMenuItem();
        jitemrosa = new javax.swing.JMenuItem();
        jitemcinza = new javax.swing.JMenuItem();
        jsobre = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Bloco de Notas");
        setForeground(new java.awt.Color(102, 102, 102));
        setResizable(false);

        jtarea.setColumns(20);
        jtarea.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        jtarea.setRows(5);
        jScrollPane1.setViewportView(jtarea);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 557, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 310, Short.MAX_VALUE)
        );

        jMenuBar1.setBackground(new java.awt.Color(204, 204, 204));

        jarquivo.setText("arquivo");

        jabrir.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_O, java.awt.event.InputEvent.CTRL_MASK));
        jabrir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/download.png"))); // NOI18N
        jabrir.setText("abrir");
        jabrir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jabrirActionPerformed(evt);
            }
        });
        jarquivo.add(jabrir);

        jnovo.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N, java.awt.event.InputEvent.CTRL_MASK));
        jnovo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/newfile_85903.png"))); // NOI18N
        jnovo.setText("novo");
        jnovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jnovoActionPerformed(evt);
            }
        });
        jarquivo.add(jnovo);

        jsalvar.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_MASK));
        jsalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/save-icon-614x460.png"))); // NOI18N
        jsalvar.setText("salvar");
        jsalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jsalvarActionPerformed(evt);
            }
        });
        jarquivo.add(jsalvar);

        jMenuBar1.add(jarquivo);

        jeditar.setText("editar");

        jcopiar.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.CTRL_MASK));
        jcopiar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/copy_paste_icon-icons.com_72426.png"))); // NOI18N
        jcopiar.setText("copiar");
        jcopiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcopiarActionPerformed(evt);
            }
        });
        jeditar.add(jcopiar);

        jrecortar.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_X, java.awt.event.InputEvent.CTRL_MASK));
        jrecortar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/fullcut_cut_scissors_4720.png"))); // NOI18N
        jrecortar.setText("recortar");
        jrecortar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jrecortarMouseClicked(evt);
            }
        });
        jrecortar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrecortarActionPerformed(evt);
            }
        });
        jeditar.add(jrecortar);

        jcolar.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_V, java.awt.event.InputEvent.CTRL_MASK));
        jcolar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/clipboard_paste.png"))); // NOI18N
        jcolar.setText("colar");
        jcolar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcolarActionPerformed(evt);
            }
        });
        jeditar.add(jcolar);

        jselecionar.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.ALT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        jselecionar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/select_icon-icons.com_65350.png"))); // NOI18N
        jselecionar.setText("selecionar");
        jselecionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jselecionarActionPerformed(evt);
            }
        });
        jeditar.add(jselecionar);

        jMenuBar1.add(jeditar);

        jMenu1.setText("fonte");
        jMenu1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu1MouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu1);

        jpesonalizar.setText("cor da fonte ");
        jpesonalizar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jpesonalizarMouseClicked(evt);
            }
        });
        jpesonalizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jpesonalizarActionPerformed(evt);
            }
        });

        jitempreto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/preto.png"))); // NOI18N
        jitempreto.setText("preto");
        jitempreto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jitempretoActionPerformed(evt);
            }
        });
        jpesonalizar.add(jitempreto);

        jitemvermelho.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/vermelho.png"))); // NOI18N
        jitemvermelho.setText("vermelho");
        jitemvermelho.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jitemvermelhoActionPerformed(evt);
            }
        });
        jpesonalizar.add(jitemvermelho);

        jitemazul.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/azul.png"))); // NOI18N
        jitemazul.setText("azul");
        jitemazul.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jitemazulActionPerformed(evt);
            }
        });
        jpesonalizar.add(jitemazul);

        jitemverde.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/verde.png"))); // NOI18N
        jitemverde.setText("verde");
        jitemverde.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jitemverdeActionPerformed(evt);
            }
        });
        jpesonalizar.add(jitemverde);

        jitemrosa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/rosa.png"))); // NOI18N
        jitemrosa.setText("rosa");
        jitemrosa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jitemrosaActionPerformed(evt);
            }
        });
        jpesonalizar.add(jitemrosa);

        jitemcinza.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/cinza.png"))); // NOI18N
        jitemcinza.setText("cinza");
        jitemcinza.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jitemcinzaActionPerformed(evt);
            }
        });
        jpesonalizar.add(jitemcinza);

        jMenuBar1.add(jpesonalizar);

        jsobre.setText("sobre");
        jsobre.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jsobreMouseClicked(evt);
            }
        });
        jsobre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jsobreActionPerformed(evt);
            }
        });
        jMenuBar1.add(jsobre);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jrecortarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jrecortarMouseClicked
       
        
        
        
    }//GEN-LAST:event_jrecortarMouseClicked

    private void jrecortarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrecortarActionPerformed
        // TODO add your handling code here:
        jtarea.selectAll();
        jtarea.cut();
    }//GEN-LAST:event_jrecortarActionPerformed

    private void jselecionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jselecionarActionPerformed
       jtarea.selectAll();
    }//GEN-LAST:event_jselecionarActionPerformed

    private void jcopiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcopiarActionPerformed
        jtarea.selectAll();
        jtarea.copy();
    }//GEN-LAST:event_jcopiarActionPerformed

    private void jcolarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcolarActionPerformed
        jtarea.selectAll();
        jtarea.paste();
    }//GEN-LAST:event_jcolarActionPerformed

    private void jsobreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jsobreActionPerformed
       
    }//GEN-LAST:event_jsobreActionPerformed

    private void jsobreMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jsobreMouseClicked
        JOptionPane.showMessageDialog(null, "Feito por Pedro Vasconcelos!","Créditos",JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_jsobreMouseClicked

    private void jnovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jnovoActionPerformed
 jtarea.setText("");
    }//GEN-LAST:event_jnovoActionPerformed

    private void jabrirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jabrirActionPerformed
       JFileChooser file = new JFileChooser(); 
file.setFileSelectionMode(JFileChooser.FILES_ONLY); 


//filtro opicional dos arquivos 
FileNameExtensionFilter filter = new FileNameExtensionFilter("Arquivos de Texto .txt", "txt");
file.setFileFilter(filter);
int i= file.showOpenDialog(null);
//caso o usuário aperte Cancelar
if (i==1){
//jlArquivo.setText(""); 
} else {
File arquivo = file.getSelectedFile();
//jlArquivo.setText(arquivo.getPath());
try {
//Indicamos o arquivo que será lido
FileReader fileReader = new FileReader(arquivo.toString());

//Criamos o objeto bufferReader que nos
// oferece o método de leitura readLine()
BufferedReader bufferedReader = new BufferedReader(fileReader);

//String que irá receber cada linha do arquivo
String linha = "";

//Fazemos um loop linha a linha no arquivo,
// enquanto ele seja diferente de null.
//O método readLine() devolve a linha na
// posicao do loop para a variavel linha.
while ( ( linha = bufferedReader.readLine() ) != null) {
//Aqui adicionamos linha por linha no arquivo 
jtarea.append(linha+"\n");
}

//liberamos o fluxo dos objetos ou fechamos o arquivo
fileReader.close();
bufferedReader.close();
} catch (IOException e) {
e.printStackTrace();
}

}
    }//GEN-LAST:event_jabrirActionPerformed

    private void jsalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jsalvarActionPerformed
        JFileChooser file = new JFileChooser(); 
file.setFileSelectionMode(JFileChooser.FILES_ONLY); 

//filtro opicional dos arquivos 
FileNameExtensionFilter filter = new FileNameExtensionFilter("Arquivos de Texto .txt", "txt");
file.setFileFilter(filter);
int i= file.showSaveDialog(null);
//caso o usuário aperte Cancelar
if (i==1){
//jlArquivo.setText(""); 
} else {
File arquivo = file.getSelectedFile();
//jlArquivo.setText(arquivo.getPath()+".txt");
try {
//Indicamos o arquivo que será lido
FileWriter fileWriter = new FileWriter(arquivo.toString()+".txt", false);

//Agora vamos usar a classe PrintWriter para escrever
//fisicamente no arquivo.
//Precisamos passar o objeto FileReader em seu construtor
PrintWriter printWriter = new PrintWriter(fileWriter);

//Agora vamos escrever no arquivo com o método println(),
// que nos permite escrever linha a linha no arquivo
printWriter.println(jtarea.getText());

//o método flush libera a escrita no arquivo
printWriter.flush();

//No final precisamos fechar o arquivo
printWriter.close(); 


} catch (IOException ex) {
Logger.getLogger(bloco.class.getName()).log(Level.SEVERE, null, ex);
}

//liberamos o fluxo dos objetos ou fechamos o arquivo


}
    }//GEN-LAST:event_jsalvarActionPerformed

    private void jpesonalizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jpesonalizarActionPerformed

    }//GEN-LAST:event_jpesonalizarActionPerformed

    private void jpesonalizarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpesonalizarMouseClicked
   /*    
        jtare.setForeground(Color.RED);    }//GEN-LAST:event_jpesonalizarMouseClicked
*/}
    private void jitempretoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jitempretoActionPerformed
           jtarea.setForeground(Color.BLACK);
    }//GEN-LAST:event_jitempretoActionPerformed

    private void jitemvermelhoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jitemvermelhoActionPerformed
           jtarea.setForeground(Color.RED);
    }//GEN-LAST:event_jitemvermelhoActionPerformed

    private void jitemazulActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jitemazulActionPerformed
           jtarea.setForeground(Color.BLUE);
    }//GEN-LAST:event_jitemazulActionPerformed

    private void jitemverdeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jitemverdeActionPerformed
           jtarea.setForeground(Color.GREEN);
    }//GEN-LAST:event_jitemverdeActionPerformed

    private void jitemrosaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jitemrosaActionPerformed
           jtarea.setForeground(Color.PINK);
    }//GEN-LAST:event_jitemrosaActionPerformed

    private void jitemcinzaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jitemcinzaActionPerformed
           jtarea.setForeground(Color.GRAY);
    }//GEN-LAST:event_jitemcinzaActionPerformed

    private void jMenu1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu1MouseClicked

        
        JFontChooser fd = new JFontChooser(this,jtarea.getFont());
fd.show();
if(fd.getReturnStatus() == fd.RET_OK){
       jtarea.setFont(fd.getFont());
}
fd.dispose();    }//GEN-LAST:event_jMenu1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(bloco.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(bloco.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(bloco.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(bloco.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new bloco().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JMenuItem jabrir;
    private javax.swing.JMenu jarquivo;
    private javax.swing.JMenuItem jcolar;
    private javax.swing.JMenuItem jcopiar;
    private javax.swing.JMenu jeditar;
    private javax.swing.JMenuItem jitemazul;
    private javax.swing.JMenuItem jitemcinza;
    private javax.swing.JMenuItem jitempreto;
    private javax.swing.JMenuItem jitemrosa;
    private javax.swing.JMenuItem jitemverde;
    private javax.swing.JMenuItem jitemvermelho;
    private javax.swing.JMenuItem jnovo;
    private javax.swing.JMenu jpesonalizar;
    private javax.swing.JMenuItem jrecortar;
    private javax.swing.JMenuItem jsalvar;
    private javax.swing.JMenuItem jselecionar;
    private javax.swing.JMenu jsobre;
    private javax.swing.JTextArea jtarea;
    // End of variables declaration//GEN-END:variables

public void setIcon() {
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/imagens/icone.png")));
        
    }

}
